# Generated by Django 3.0.3 on 2020-03-09 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=64, verbose_name='科目类别')),
            ],
            options={
                'verbose_name_plural': '科目类别',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companycode', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='公司编码')),
                ('companyname', models.CharField(max_length=64, verbose_name='公司名')),
                ('parentcompany', models.BooleanField(default=True, verbose_name='父级公司')),
            ],
            options={
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MysqlView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='序号')),
                ('accountname', models.CharField(max_length=64, verbose_name='科目名')),
                ('amount', models.IntegerField(max_length=256, verbose_name='金额')),
                ('companyname', models.CharField(max_length=64, verbose_name='公司名')),
                ('accountdate', models.DateField(verbose_name='会计日期')),
                ('versionname', models.CharField(max_length=64, verbose_name='版本号')),
                ('vaild', models.BooleanField(verbose_name='有效标记')),
                ('typename', models.CharField(max_length=30, verbose_name='科目类别')),
            ],
            options={
                'db_table': 'mysqlview',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('submittdate', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('accountdate', models.DateField(verbose_name='会计期间')),
                ('actualorbudget', models.BooleanField(default=True, verbose_name='实际数')),
                ('versionname', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='版本ID')),
                ('vaild', models.NullBooleanField(verbose_name='作废标记')),
                ('companycode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.Company')),
            ],
            options={
                'verbose_name_plural': '版本',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='员工号')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='电子邮件')),
                ('companycode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.Company')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodrate', models.FloatField(verbose_name='期间汇率')),
                ('pointrate', models.FloatField(verbose_name='即时汇率')),
                ('currencydate', models.DateField(verbose_name='会计期间')),
                ('aftercur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.Currency')),
                ('originalcur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ori_cur', to='collector.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='科目编码')),
                ('accountname', models.CharField(max_length=128, verbose_name='科目名称')),
                ('parentaccount', models.BooleanField(default=False, verbose_name='父级科目')),
                ('accounttypeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.AccountType')),
            ],
            options={
                'verbose_name_plural': '科目',
            },
        ),
        migrations.CreateModel(
            name='BudgetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, verbose_name='预算数')),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.Account')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Version')),
            ],
            options={
                'verbose_name_plural': '预算数',
                'unique_together': {('version', 'accountid')},
            },
        ),
        migrations.CreateModel(
            name='ActualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, verbose_name='实际数')),
                ('accountid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.Account')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Version')),
            ],
            options={
                'verbose_name_plural': '实际发生数',
                'unique_together': {('version', 'accountid')},
            },
        ),
    ]
