# Generated by Django 3.0.3 on 2020-03-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualdata',
            name='amount',
            field=models.FloatField(default=0, verbose_name='实际数'),
        ),
    ]
