# Generated by Django 3.0.3 on 2020-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20200314_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companybu',
            new_name='bu',
        ),
        migrations.AlterField(
            model_name='company',
            name='isvalid',
            field=models.BooleanField(default=True, verbose_name='有效标记'),
        ),
    ]
