# Generated by Django 3.0.3 on 2020-03-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20200314_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='displayname',
            field=models.CharField(max_length=128, null=True, verbose_name='显示名称'),
        ),
    ]
