# Generated by Django 3.0.3 on 2020-03-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20200309_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': '科目维护'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'verbose_name_plural': '科目类别维护'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': '公司维护'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': '币种维护'},
        ),
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'verbose_name_plural': '汇率维护'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户维护'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name_plural': '版本管理'},
        ),
        migrations.AddField(
            model_name='currency',
            name='currencyname',
            field=models.CharField(default=1, max_length=10, verbose_name='记账币'),
            preserve_default=False,
        ),
    ]
