# Generated by Django 3.0.3 on 2020-03-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20200309_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysqlview',
            options={'managed': False, 'verbose_name_plural': '经营分析主要指标表'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='currencyname',
            field=models.CharField(max_length=10, unique=True, verbose_name='记账币'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='aftercur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aft_cur', to='collector.Currency'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='currencydate',
            field=models.DateField(verbose_name='汇率日期'),
        ),
    ]
